### ISSUE TITLE
Update for 0.8

### ISSUE THREAD

**Issue by jimmylee** [JonDum/polymer-loader#2]
Hey @JonDum I've been playing with your loader and saw some places that needed update. I also don't mind submitting a PR just wanted to discuss first and check if you guys were alive :)

**Back in 0.5**

``` js
<polymer-element name="register-me">
  <template>
    <div>Hello from my local DOM</div>
  </template>
  <script>
    Polymer();
  </script>
</polymer-element>
```

**Now in 0.8** https://www.polymer-project.org/0.8/docs/migration.html

``` js
<dom-module id="register-me">
  <template>
    <div>Hello from my local DOM</div>
  </template>
</dom-module>

<script>
  Polymer({is: "register-me"});
</script>
```

**In your code**

``` js
// line 47
"\t\tel.innerHTML = template.replace('</polymer-element>',

// line 73
<polymer-element name=\""+elementName+"\">
```

All need to be swapped to the new `dom-module` and `id` conventions.

Thanks!!

**Comment by sarendipitee** [comment]
Ugh polymer. -_-

Yea that's fine. I'm traveling right now, but I have my phone so can accept
a PR/update NPM no problem.

**Comment by jimmylee** [comment]
Radical I'll jump on this.

Edit: You know what, I misinterpreted their website and assumed that `0.8` was an official release. Therefore people who are using Polymer-loader would be probably better off using `0.5.5`. Sorry about jumping the gun on this one.

**Comment by ivstas** [comment]
Since polymer 1.0 is released, maybe update to 1.0.

**Comment by Nevraeka** [comment]
:+1: @ivstas

**Comment by du5rte** [comment]
:+1: @ivstas

**Comment by sarendipitee** [comment]
@Granze Took the liberty of updating this out via #5.

Is everything all good in the hood for you guys here?

**Comment by Birowsky** [comment]
This delay kinda confuses me. Why no update. Where is everybody :/

**Comment by sarendipitee** [comment]
@Birowsky What confuses you exactly? I don't use Polymer anymore so this project is at the whim of the community.

**Comment by Birowsky** [comment]
You seem quite busy. No worries, I’ll see what I can do by my own, and get back to ya with concrete questions.

Have fun!

**Comment by aruntk** [comment]
I've built a package to handle polymer/webcomponents files and html imports (with HMR support)

https://github.com/aruntk/wc-loader. check out.

Demo https://github.com/aruntk/polymer-webpack-demo

**Comment by sarendipitee** [comment]
Now supports polymer 3.0
